version: "3.9"
services:
  backend:
    build: ./backend
    container_name: tf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./terraform_templates:/app/terraform_templates
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1

  frontend:
    build: ./frontend
    container_name: tf-frontend
    ports:
      - "4173:5173"
    depends_on:
      - backend
